services:
  db:
    image: postgres
    ports:
      - "5544:5432"
    environment:
      - POSTGRES_PASSWORD=Password
      - POSTGRES_DB=techforb
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
  web-api:
    build: ./techforb-webapi
    ports:
      - "8091:8080"
    environment:
      - server.port=8080
    #   - spring.jpa.hibernate.ddl-auto=none
      - spring.datasource.url=jdbc:postgresql://db:5432/techforb
      - spring.datasource.username=postgres
      - spring.datasource.password=Password
    #   - spring.jpa.show-sql=false
    #   - spring.jpa.properties.hibernate.format_sql=false
      - jwt.secret-key=msjklksduywerlkjlj3kj239845lkjsku3jkanjkh23
      - jwt.expiration-time=7200000
      - jwt.expiration-time-refresh=7200000
